resource_types:
- name: cf_cli_resource
  type: docker-image
  source:
    repository: pivotalpa/cf-cli-resource
    tag: latest

resources:
- name: app_sources
  type: git
  source:
    uri: http://192.168.58.7:30080/root/<my-gitlab-project>.git
    username: {{gitlab_username}}
    password: {{gitlab_password}}
    branch: master
  check_every: 10s

- name: cloud_foundry
  type: cf_cli_resource
  source:
    api: https://api.run.pivotal.io
    username: {{cf_username}}
    password: {{cf_password}}
    org: <my_cf_org>
    space: <my_cf_space>
    skip_cert_check: false

jobs:
  - name: deploy-app
    public: true
    serial: true
    plan:
    - get: app_sources
      version: every
      trigger: true
    - put: cf-push
      resource: cloud_foundry
      params:
        command: zero-downtime-push
        path: app_sources/website/
        manifest: app_sources/manifest.yml
        current_app_name: <my_app_name>
